db2 connect to salplanp user salplanp using $1 
 
db2 export to data/temp_monthly_data_2016A.txt of del messages logs/log_newforecast.txt "select SPLAN_MODE, SPLAN_TYPE, '2016-01-01' as SPLAN_START_DT, SPLAN_YEAR_DT, SHELL_CD, SUM_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SPLAN_EMP_NO, SPLAN_EMP_MO1, SPLAN_EMP_MO2, SPLAN_EMP_MO3, SPLAN_EMP_MO4, SPLAN_EMP_MO5, SPLAN_EMP_MO6, SPLAN_EMP_MO7, SPLAN_EMP_MO8, SPLAN_EMP_MO9, SPLAN_EMP_MO10, SPLAN_EMP_MO11, SPLAN_EMP_MO12, SPLAN_EMP_TOTAL from temp_monthly_data where splan_start_dt='01/01/2015' and splan_mode='A' and splan_year_dt='01/01/2016'"
 
db2 export to data/temp_monthly_data_2017A.txt of del messages logs/log_newforecast.txt "select SPLAN_MODE, SPLAN_TYPE, '2016-01-01' as SPLAN_START_DT, '2017-01-01' as SPLAN_YEAR_DT, SHELL_CD, SUM_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SPLAN_EMP_NO, SPLAN_EMP_MO12 as SPLAN_EMP_MO1, SPLAN_EMP_MO12 as SPLAN_EMP_MO2, SPLAN_EMP_MO12 as SPLAN_EMP_MO3, SPLAN_EMP_MO12 as SPLAN_EMP_MO4, SPLAN_EMP_MO12 as SPLAN_EMP_MO5, SPLAN_EMP_MO12 as SPLAN_EMP_MO6, SPLAN_EMP_MO12 as SPLAN_EMP_MO7, SPLAN_EMP_MO12 as SPLAN_EMP_MO8, SPLAN_EMP_MO12 as SPLAN_EMP_MO9,SPLAN_EMP_MO12 as SPLAN_EMP_MO10, SPLAN_EMP_MO12 as SPLAN_EMP_MO11, SPLAN_EMP_MO12 as SPLAN_EMP_MO12, 0 as SPLAN_EMP_TOTAL from temp_monthly_data where splan_start_dt='01/01/2015' and splan_mode='A' and splan_year_dt='01/01/2016'"
 
db2 export to data/temp_sal_monthly_exp_2016A.txt of del messages logs/log_newforecast.txt "select SPLAN_EMP_NO, '2016-01-01' as SPLAN_START_DT, SPLAN_MODE, SHELL_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SUM_CD, SPLAN_EMP_SAL_EXP_MO1, SPLAN_EMP_SAL_EXP_MO2, SPLAN_EMP_SAL_EXP_MO3, SPLAN_EMP_SAL_EXP_MO4, SPLAN_EMP_SAL_EXP_MO5, SPLAN_EMP_SAL_EXP_MO6, SPLAN_EMP_SAL_EXP_MO7, SPLAN_EMP_SAL_EXP_MO8, SPLAN_EMP_SAL_EXP_MO9, SPLAN_EMP_SAL_EXP_MO10, SPLAN_EMP_SAL_EXP_MO11, SPLAN_EMP_SAL_EXP_MO12, SPLAN_EMP_SAL_EXP_TOTAL, SPLAN_YEAR_DT from temp_sal_monthly_exp where  splan_start_dt='01/01/2015' and splan_mode='A' and splan_year_dt='01/01/2016'"
 
db2 export to data/temp_sal_monthly_exp_2017A.txt of del messages logs/log_newforecast.txt "select SPLAN_EMP_NO, '2016-01-01' as SPLAN_START_DT, SPLAN_MODE, SHELL_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SUM_CD, decimal(round((SPLAN_EMP_MO12/260) * 22, 2),11,2) as SPLAN_EMP_SAL_EXP_MO1, decimal(round((SPLAN_EMP_MO12/260) * 20, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO2, decimal(round((SPLAN_EMP_MO12/260) * 23, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO3, decimal(round((SPLAN_EMP_MO12/260) * 20, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO4, decimal(round((SPLAN_EMP_MO12/260) * 23, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO5, decimal(round((SPLAN_EMP_MO12/260) * 22, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO6, decimal(round((SPLAN_EMP_MO12/260) * 21, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO7, decimal(round((SPLAN_EMP_MO12/260) * 23, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO8, decimal(round((SPLAN_EMP_MO12/260) * 21, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO9, decimal(round((SPLAN_EMP_MO12/260) * 22, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO10, decimal(round((SPLAN_EMP_MO12/260) * 22, 2),11,2) as  SPLAN_EMP_SAL_EXP_MO11, decimal(round((SPLAN_EMP_MO12/260) * 21, 2),11,2) as SPLAN_EMP_SAL_EXP_MO12, decimal(round((SPLAN_EMP_MO12/260) * 260,2),11,2) as SPLAN_EMP_SAL_EXP_TOTAL, '2017-01-01' as SPLAN_YEAR_DT  from temp_monthly_data  where  splan_start_dt='01/01/2015' and splan_mode='A' and splan_year_dt='01/01/2016' and splan_type='AS'"
 
db2 export to data/temp_sal_increase_2016A.txt of del messages logs/log_newforecast.txt "select SPLAN_INCRS_ID, SPLAN_EMP_NO, '2016-01-01' as SPLAN_START_DT, SAL_INCRS_EFF_DT, SPLAN_MODE, ANN_SAL_AMT, SPLAN_NEW_ANN_SAL_AMT, SAL_INCRS_PCT, SAL_INCRS_AMT, PERF_SCORE_CD, SAL_CHNG_CD, SHELL_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SUM_CD, SPLAN_USER_ID, SPLAN_TRANS_DT, SPLAN_INCRS_COMMENT, SPLAN_REF_INCRS_ID from temp_sal_increase where splan_start_dt='01/01/2015' and splan_mode='A'  "
 
db2 export to data/temp_sal_increase_hist_2016A.txt of del messages logs/log_newforecast.txt "select SPLAN_INCRS_ID, SPLAN_EMP_NO, '2016-01-01' as SPLAN_START_DT, SAL_INCRS_EFF_DT, SPLAN_MODE, ANN_SAL_AMT, SPLAN_NEW_ANN_SAL_AMT, SAL_INCRS_PCT, SAL_INCRS_AMT, PERF_SCORE_CD, SAL_CHNG_CD, SHELL_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SUM_CD, SPLAN_USER_ID, SPLAN_TRANS_DT, SPLAN_INCRS_COMMENT, SPLAN_REF_INCRS_ID from temp_sal_increase_hist where splan_start_dt='01/01/2015' and splan_mode='A' and splan_incrs_comment like 'Deleted upon Reconcile%' "
 
db2 export to data/temp_adjustment_2016A.txt of del messages logs/log_newforecast.txt "select SPLAN_EMP_NO, SPLAN_MODE, SPLAN_ADJ_TYPE, SPLAN_ADJ_EFF_DT, SPLAN_TRANS_DT, SPLAN_REPLC_DT, EMP_FIRST_NM, EMP_LAST_NM, JOB_CD, FLSA_CD, ANN_SAL_AMT, SHELL_CD, SUM_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SPLAN_PREV_SHELL_CD, SPLAN_PREV_SUM_CD, SPLAN_PREV_WW_CO_NO, SPLAN_PREV_BRCH_CD, SPLAN_PREV_DEPT_NO, SPLAN_USER_ID, SPLAN_ADJ_APPRVD_IND, SPLAN_TRANS_ID, '2016-01-01' as SPLAN_START_DT, SPLAN_PREV_ADJ_TYPE, SPLAN_PREV_EFF_DT, SPLAN_EMP_REF_NO, SPLAN_PREV_TRANS_ID, SPLAN_EMP_REF_NO_N, SPLAN_REF_TRANS_ID from temp_adjustment where splan_start_dt='01/01/2015' and splan_mode='A'"
 
db2 export to data/temp_adj_hist_2016A.txt of del messages logs/log_newforecast.txt "select SPLAN_EMP_NO, SPLAN_MODE, SPLAN_ADJ_TYPE, SPLAN_ADJ_EFF_DT, SPLAN_TRANS_DT, SPLAN_REPLC_DT, EMP_FIRST_NM, EMP_LAST_NM, JOB_CD, FLSA_CD, ANN_SAL_AMT, SHELL_CD, SUM_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SPLAN_PREV_SHELL_CD, SPLAN_PREV_SUM_CD, SPLAN_PREV_WW_CO_NO, SPLAN_PREV_BRCH_CD, SPLAN_PREV_DEPT_NO, SPLAN_USER_ID, SPLAN_ADJ_APPRVD_IND, SPLAN_TRANS_ID, '2016-01-01' as SPLAN_START_DT, SPLAN_PREV_ADJ_TYPE, SPLAN_PREV_EFF_DT, SPLAN_EMP_REF_NO, SPLAN_PREV_TRANS_ID, SPLAN_EMP_REF_NO_N, SPLAN_REF_TRANS_ID from temp_adj_hist where splan_start_dt='01/01/2015' and splan_mode='A' and splan_adj_type in ('RE','RO')"

db2 export to data/tsal_plan_payrollinfo_2016A.txt of ixf messages logs/log_newforecast_tpayroll_info.txt "select SPLAN_EMP_NO, '2016-01-01' as SPLAN_START_DT, SPLAN_MODE, SOC_SEC_NO, OLD_SOC_SEC_NO, SPLAN_PREV_EMP_NO, EMP_FIRST_NM, EMP_LAST_NM, EMP_M_I_NM, EMP_STATUS_CD, REGION_CD, SHELL_CD, SUM_CD, CO_PRFX_CD, WW_CO_NO, BRCH_CD, DEPT_NO, SERVICE_DT, LAST_PERF_DT, NEXT_REVIEW_DT, FINAL_DT_ON_PAYROLL, ACTION_CD, JOB_CD, PERF_SCORE_CD, FLSA_CD,case when splan_emp_type not in ('A','O') then splan_ann_forcast_amt else ann_sal_amt end  as ANN_SAL_AMT,   ANN_SAL_CHNG_AMT, SAL_INCRS_PCT, SAL_CHNG_CD, CO_CAR_PRIVS_IND, SPLAN_ANN_BUDGETD_AMT as SPLAN_ANN_FORCAST_AMT, SPLAN_ANN_BUDGETD_AMT, SPLAN_COBRDEPT, SPLAN_TRANSF_IND, SPLAN_ADJ_TYPE, SPLAN_ADJ_EFF_DT, SPLAN_TRANS_ID, SPLAN_CREATED_BY, SPLAN_SYS_COMMENT, SPLAN_BUDGET_HC_COUNT as SPLAN_FORECAST_HC_COUNT, SPLAN_BUDGET_HC_COUNT, SPLAN_ACTIVE_STATUS, ann_sal_amt as PREV_YR_ANN_SAL_AMT, SPLAN_USER_COMMENT, SPLAN_EMP_TYPE, EMPLOYEE_ID from tsal_plan_payroll_info where splan_start_dt='01/01/2015' and splan_mode='A'"

db2 connect reset
